[project]
name = "portfolio-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tomasz Przybylo", email = "tomasz.przybylo3@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.97",
    "faker>=40.39.0",
    "psycopg2-binary>=2.9.13",
]

[project.scripts]
portfolio-project = "portfolio_project:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
